version: '3.8'

services:
  # MongoDB Database for development
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: alioth
    volumes:
      - mongo_dev_data:/data/db
    networks:
      - alioth-dev-network

  # Redis for development
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server --appendonly yes
    volumes:
      - redis_dev_data:/data
    networks:
      - alioth-dev-network

  # MongoDB Admin Interface
  mongo-express:
    image: mongo-express:latest
    restart: unless-stopped
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongo
    networks:
      - alioth-dev-network

volumes:
  mongo_dev_data:
  redis_dev_data:

networks:
  alioth-dev-network:
    driver: bridge
